import type { Request, Response } from "express";
import { sendInternalError } from "../../utils/apiErrors";
import * as service from "./service";
import { parseSubjectId, studentSubjectPayloadSchema } from "./validators";
function ids(req: Request) { return { tutorId: (req as any).tutorId as string, studentId: String(req.params.studentId) }; }
export async function list(req: Request, res: Response) { try { const { tutorId, studentId } = ids(req); return res.json(await service.list(tutorId, studentId)); } catch (err: any) { if (err instanceof service.StudentSubjectError) return res.status(err.status).json({ message: err.message }); return sendInternalError(req, res, err, "routes.failed_to_fetch_student_subjects", "Failed to fetch student subjects"); } }
export async function add(req: Request, res: Response) { try { const { tutorId, studentId } = ids(req); const payload = studentSubjectPayloadSchema.parse(req.body || {}); return res.status(201).json(await service.add(tutorId, studentId, payload)); } catch (err: any) { if (err instanceof service.StudentSubjectError) return res.status(err.status).json({ message: err.message }); return res.status(400).json({ message: err.message || "Failed to add subject" }); } }
export async function update(req: Request, res: Response) { try { const { tutorId, studentId } = ids(req); const subjectId = parseSubjectId(String(req.params.subjectId)); if (subjectId === null) return res.status(400).json({ message: "Invalid subject id" }); const payload = studentSubjectPayloadSchema.parse(req.body || {}); const row = await service.update(tutorId, studentId, subjectId, payload); if (!row) return res.status(404).json({ message: "Student subject not found" }); return res.json(row); } catch (err: any) { if (err instanceof service.StudentSubjectError) return res.status(err.status).json({ message: err.message }); return res.status(400).json({ message: err.message || "Failed to update subject" }); } }
export async function remove(req: Request, res: Response) { try { const { tutorId, studentId } = ids(req); const subjectId = parseSubjectId(String(req.params.subjectId)); if (subjectId === null) return res.status(400).json({ message: "Invalid subject id" }); return res.json(await service.remove(tutorId, studentId, subjectId)); } catch (err: any) { if (err instanceof service.StudentSubjectError) return res.status(err.status).json({ message: err.message }); return res.status(400).json({ message: err.message || "Failed to delete subject" }); } }
