import { describe, expect, it } from "vitest";
import { pdfRubricSchema, markerResultSchema, verificationResultSchema } from "../shared/pdfMarking";
import { reconcilePdfMarking, buildPdfMarkingIdempotencyKey } from "../server/services/pdfReconciliation";
import { getPdfMarkingConfig } from "../server/services/pdfMarkingConfig";
import { normalizedToPdfRect } from "../server/services/pdfAnnotationRenderer";

const rubric = pdfRubricSchema.parse({ assessmentTitle: "Test", totalMarks: 2, questions: [{ questionId: "q1", label: "Q1", prompt: "", pageReferences: [1], maximumMarks: 2, answerType: "numeric", syllabusTags: [], acceptedAlternatives: [], rubricItems: [{ rubricItemId: "i1", sequence: 1, description: "method", maximumMarks: 1, markType: "method", dependencies: [], errorCarriedForwardAllowed: true, unitsRequired: false }, { rubricItemId: "i2", sequence: 2, description: "accuracy", maximumMarks: 1, markType: "accuracy", dependencies: ["i1"], errorCarriedForwardAllowed: false, unitsRequired: true }] }] });
const d = (id: string, item: string, marks: number, verdict = "correct") => ({ decisionId: id, questionLabel: "Q1", rubricItemId: item, verdict, awardedMarks: marks, maximumMarks: 1, confidencePct: 90, evidence: [{ pageNumber: 1, xBp: 100, yBp: 100, widthBp: 100, heightBp: 100, transcribedEvidence: "work" }], explanation: "evidence", annotation: marks ? "tick" : "cross" });

describe("PDF marking contracts", () => {
  it("validates rubric totals and unique item ids", () => { expect(rubric.totalMarks).toBe(2); expect(() => pdfRubricSchema.parse({ ...rubric, totalMarks: 3 })).toThrow(); });
  it("rejects same provider by default", () => { const cfg = getPdfMarkingConfig({ PDF_DUAL_MARKING_ENABLED: "true", PDF_MARKER_A_PROVIDER: "openai", PDF_MARKER_A_MODEL: "a", PDF_MARKER_B_PROVIDER: "openai", PDF_MARKER_B_MODEL: "b" } as any); expect(cfg.configured).toBe(false); });
  it("builds stable idempotency keys", () => { expect(buildPdfMarkingIdempotencyKey({ submissionUploadId: 1, submissionVersion: 2, contentHash: "abc", rubricVersionId: 3 })).toBe("mark_submission:1:2:abc:3"); });
  it("deterministically accepts matching verified marks", () => { const markerA = markerResultSchema.parse({ decisions: [d("a1", "i1", 1), d("a2", "i2", 1)] }); const markerB = markerResultSchema.parse({ decisions: [d("b1", "i1", 1), d("b2", "i2", 1)] }); const verifierA = verificationResultSchema.parse({ decisions: [{ targetDecisionId: "b1", verdict: "accept", rationale: "supported" }, { targetDecisionId: "b2", verdict: "accept", rationale: "supported" }] }); const verifierB = verificationResultSchema.parse({ decisions: [{ targetDecisionId: "a1", verdict: "accept", rationale: "supported" }, { targetDecisionId: "a2", verdict: "accept", rationale: "supported" }] }); const result = reconcilePdfMarking({ rubric, markerA, markerB, verifierA, verifierB }); expect(result.proposedScore).toBe(2); expect(result.reviewItems).toHaveLength(0); });
  it("creates review items for disagreements and unreadable evidence", () => { const markerA = markerResultSchema.parse({ decisions: [d("a1", "i1", 1), d("a2", "i2", 0, "unreadable")] }); const markerB = markerResultSchema.parse({ decisions: [d("b1", "i1", 0), d("b2", "i2", 0, "incorrect")] }); const verifierA = verificationResultSchema.parse({ decisions: [{ targetDecisionId: "b1", verdict: "reject", rationale: "not supported" }, { targetDecisionId: "b2", verdict: "uncertain", rationale: "unclear" }] }); const verifierB = verificationResultSchema.parse({ decisions: [{ targetDecisionId: "a1", verdict: "accept", rationale: "supported" }, { targetDecisionId: "a2", verdict: "uncertain", rationale: "unclear" }] }); const result = reconcilePdfMarking({ rubric, markerA, markerB, verifierA, verifierB }); expect(result.proposedScore).toBe(0); expect(result.reviewItems.length).toBeGreaterThan(0); });
  it("converts normalized coordinates to PDF coordinates", () => { const rect = normalizedToPdfRect({ getWidth: () => 200, getHeight: () => 100 }, { xBp: 5000, yBp: 0, widthBp: 1000, heightBp: 1000 }); expect(rect).toEqual({ x: 100, y: 90, width: 20, height: 10 }); });
});
