import { useState, useEffect, useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useLocation } from "wouter";
import { authFetch } from "@/lib/supabase";
import { useSupabaseSession } from "@/hooks/use-supabase-session";
import { getSubjectColor } from "@/lib/subjectColors";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  ArrowLeft, Sparkles, Loader2, BookOpen, TrendingUp,
  AlertTriangle, CheckCircle2, Target,
} from "lucide-react";
import DOMPurify from "dompurify";
import { toProperCase } from "@/lib/utils";
import { ThemeToggle } from "@/components/ThemeToggle";

interface ReportWithQuiz {
  id: number;
  quizId: number;
  studentId: string | null;
  studentName: string;
  score: number;
  status: string;
  aiFeedbackHtml: string | null;
  createdAt: string;
  quiz: { id: number; title: string; topic: string | null };
}

interface SubmissionWithQuiz {
  id: number;
  studentId: number;
  quizId: number;
  totalScore: number;
  maxPossibleScore: number;
  submittedAt: string;
  quiz: { id: number; title: string; subject: string | null };
}

export default function SomaChatPage() {
  const [, setLocation] = useLocation();
  const [analysis, setAnalysis] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const reportRef = useRef<HTMLDivElement>(null);
  const autoGeneratedRef = useRef(false);

  const { session, userId } = useSupabaseSession();
  const displayName = toProperCase(session?.user?.user_metadata?.display_name || session?.user?.email?.split("@")[0] || "Student");

  const { data: reports = [], isLoading: reportsLoading } = useQuery<ReportWithQuiz[]>({
    queryKey: ["/api/student/reports", userId],
    queryFn: async () => {
      if (!userId) return [];
      const res = await authFetch("/api/student/reports");
      if (!res.ok) return [];
      return res.json();
    },
    enabled: !!userId,
  });

  const { data: submissions = [], isLoading: subsLoading } = useQuery<SubmissionWithQuiz[]>({
    queryKey: ["/api/student/submissions", userId],
    queryFn: async () => {
      if (!userId) return [];
      const res = await authFetch("/api/student/submissions");
      if (!res.ok) return [];
      return res.json();
    },
    enabled: !!userId,
  });

  const isDataLoading = reportsLoading || subsLoading;

  const hasData = reports.length > 0 || submissions.length > 0;

  // Auto-trigger analysis when data finishes loading
  useEffect(() => {
    if (!isDataLoading && hasData && !analysis && !loading && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      generateAnalysis();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isDataLoading, hasData]);

  const generateAnalysis = async () => {
    setLoading(true);
    setError("");
    setAnalysis("");

    try {
      // Build a comprehensive summary of all student performance
      const reportSummaries = reports.map((r) => ({
        quiz: r.quiz.title,
        topic: r.quiz.topic || "General",
        score: r.score,
        maxScore: 100,
        percentage: r.score,
        status: r.status,
        feedback: r.aiFeedbackHtml
          ? r.aiFeedbackHtml.replace(/<[^>]*>/g, "").slice(0, 500)
          : "No feedback available",
        date: r.createdAt,
      }));

      const submissionSummaries = submissions.map((s) => ({
        quiz: s.quiz.title,
        subject: s.quiz.subject || "General",
        score: s.totalScore,
        maxScore: s.maxPossibleScore,
        percentage: s.maxPossibleScore > 0 ? Math.round((s.totalScore / s.maxPossibleScore) * 100) : 0,
        date: s.submittedAt,
      }));

      const overallAvg = [...reportSummaries.map((r) => r.percentage), ...submissionSummaries.map((s) => s.percentage)];
      const avgScore = overallAvg.length > 0 ? Math.round(overallAvg.reduce((a, b) => a + b, 0) / overallAvg.length) : 0;

      const payload = {
        message: JSON.stringify({
          instruction: "Analyze this student's complete academic performance across all their quizzes and assessments. Aggregate all the individual analyses and quiz results into ONE comprehensive standing report.",
          studentName: displayName,
          overallAveragePercentage: avgScore,
          totalAssessments: reportSummaries.length + submissionSummaries.length,
          somaQuizResults: reportSummaries,
          regularQuizResults: submissionSummaries,
          requestedSections: [
            "Overall Academic Standing (grade/tier and what it means)",
            "Subject-by-Subject Breakdown (strengths per subject)",
            "Critical Weak Areas (specific concepts to revisit with priority ranking)",
            "Fundamental Gaps (core foundational concepts that need reinforcement)",
            "Personalized Study Plan (week-by-week recommendations)",
            "Motivational Summary (encouragement based on progress trends)",
          ],
        }),
      };

      const res = await fetch("/api/student/ai-analysis", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      // Guard against HTML responses (SPA catch-all returning index.html)
      const contentType = res.headers.get("content-type") || "";
      if (!res.ok || !contentType.includes("application/json")) {
        // Fall back: use the orchestrator via a direct prompt without admin auth
        // Build the analysis client-side from existing feedback
        const feedbackParts = reports
          .filter((r) => r.aiFeedbackHtml && r.status !== "pending")
          .map((r) => `<h3>${r.quiz.title} (${r.score}%)</h3>${r.aiFeedbackHtml}`);

        if (feedbackParts.length === 0 && submissions.length === 0) {
          setError("No completed assessments with feedback found. Complete some quizzes first.");
          return;
        }

        // Generate a local aggregated summary
        const subjectScores: Record<string, { total: number; earned: number; count: number }> = {};
        submissions.forEach((s) => {
          const subj = s.quiz.subject || "General";
          if (!subjectScores[subj]) subjectScores[subj] = { total: 0, earned: 0, count: 0 };
          subjectScores[subj].total += s.maxPossibleScore;
          subjectScores[subj].earned += s.totalScore;
          subjectScores[subj].count++;
        });
        reports.forEach((r) => {
          const subj = r.quiz.topic || "General";
          if (!subjectScores[subj]) subjectScores[subj] = { total: 0, earned: 0, count: 0 };
          subjectScores[subj].total += 100;
          subjectScores[subj].earned += r.score;
          subjectScores[subj].count++;
        });

        let html = `<h2>Academic Standing Report for ${displayName}</h2>`;
        html += `<h3>Overall Performance</h3>`;
        html += `<p>Average score across <strong>${overallAvg.length} assessments</strong>: <strong>${avgScore}%</strong></p>`;
        html += `<p>Standing: <strong>${avgScore >= 80 ? "Excellent" : avgScore >= 65 ? "Good" : avgScore >= 50 ? "Satisfactory" : "Needs Improvement"}</strong></p>`;

        html += `<h3>Subject Breakdown</h3><ul>`;
        for (const [subj, data] of Object.entries(subjectScores)) {
          const pct = data.total > 0 ? Math.round((data.earned / data.total) * 100) : 0;
          html += `<li><strong>${subj}</strong>: ${pct}% across ${data.count} assessment${data.count > 1 ? "s" : ""}</li>`;
        }
        html += `</ul>`;

        if (feedbackParts.length > 0) {
          html += `<h3>Individual Assessment Feedback</h3>`;
          html += feedbackParts.join("<hr/>");
        }

        html += `<h3>Recommendations</h3><ul>`;
        for (const [subj, data] of Object.entries(subjectScores)) {
          const pct = data.total > 0 ? Math.round((data.earned / data.total) * 100) : 0;
          if (pct < 60) {
            html += `<li>Revisit <strong>${subj}</strong> fundamentals - current average is ${pct}%</li>`;
          }
        }
        if (Object.values(subjectScores).every(d => d.total > 0 && (d.earned / d.total) >= 0.6)) {
          html += `<li>Strong performance across all subjects. Focus on pushing for excellence in weaker areas.</li>`;
        }
        html += `</ul>`;

        setAnalysis(html);
        return;
      }

      const data = await res.json();
      let reply = data.reply || "";
      // Clean up code fences from AI response
      reply = reply.replace(/^```(?:html)?\s*/i, "").replace(/\s*```\s*$/i, "").trim();
      if (data.metadata) {
        reply += `<hr style="margin-top: 30px; border-color: #334155;"/><p style="font-size: 10px; color: #64748b; text-align: center; text-transform: uppercase; letter-spacing: 0.1em;">Generated by ${data.metadata.provider} (${data.metadata.model}) in ${(data.metadata.durationMs / 1000).toFixed(2)}s</p>`;
      }
      setAnalysis(reply);
    } catch (err: unknown) {
      const msg = (err instanceof Error && err.message) || "Failed to generate analysis. Please try again.";
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  if (!session) {
    return (
      <div className="min-h-screen flex items-center justify-center px-4">
        <div className="bg-card/80 backdrop-blur-md border border-card-border rounded-2xl p-8 text-center max-w-md">
          <Sparkles className="w-12 h-12 mx-auto text-emerald-400 mb-4" />
          <h2 className="text-xl font-bold text-foreground mb-2">SOMA Tutor</h2>
          <p className="text-sm text-muted-foreground mb-6">Please log in to access your personalized analysis.</p>
          <Link href="/login">
            <Button className="glow-button">Log In</Button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <header className="border-b border-card-border/60 bg-background/95 backdrop-blur-xl sticky top-0 z-20">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/dashboard">
              <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground">
                <ArrowLeft className="w-4 h-4 mr-1" />
                Dashboard
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-emerald-400" />
              <h1 className="text-lg font-bold text-emerald-300">SOMA Tutor</h1>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <p className="text-sm text-muted-foreground">{displayName}</p>
            <ThemeToggle size="sm" />
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8 space-y-6">
        {/* Stats overview */}
        {!isDataLoading && hasData && (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-card/80 backdrop-blur-md border border-card-border rounded-2xl p-5 text-center">
              <BookOpen className="w-5 h-5 mx-auto text-violet-400 mb-2" />
              <p className="text-2xl font-bold text-foreground">{reports.length + submissions.length}</p>
              <p className="text-xs text-muted-foreground uppercase tracking-wider">Assessments</p>
            </div>
            <div className="bg-card/80 backdrop-blur-md border border-card-border rounded-2xl p-5 text-center">
              <TrendingUp className="w-5 h-5 mx-auto text-emerald-400 mb-2" />
              <p className="text-2xl font-bold text-foreground">
                {(() => {
                  const scores = [
                    ...submissions.map(s => s.maxPossibleScore > 0 ? Math.round((s.totalScore / s.maxPossibleScore) * 100) : 0),
                    ...reports.map(r => r.score),
                  ];
                  return scores.length > 0 ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : 0;
                })()}%
              </p>
              <p className="text-xs text-muted-foreground uppercase tracking-wider">Average</p>
            </div>
            <div className="bg-card/80 backdrop-blur-md border border-card-border rounded-2xl p-5 text-center">
              <CheckCircle2 className="w-5 h-5 mx-auto text-cyan-400 mb-2" />
              <p className="text-2xl font-bold text-foreground">
                {reports.filter(r => r.aiFeedbackHtml && r.status !== "pending").length}
              </p>
              <p className="text-xs text-muted-foreground uppercase tracking-wider">SOMA Reports</p>
            </div>
            <div className="bg-card/80 backdrop-blur-md border border-card-border rounded-2xl p-5 text-center">
              <Target className="w-5 h-5 mx-auto text-amber-400 mb-2" />
              <p className="text-2xl font-bold text-foreground">
                {new Set([
                  ...submissions.map(s => s.quiz.subject).filter(Boolean),
                  ...reports.map(r => r.quiz.topic).filter(Boolean),
                ]).size}
              </p>
              <p className="text-xs text-muted-foreground uppercase tracking-wider">Subjects</p>
            </div>
          </div>
        )}

        {/* Generate button */}
        <div className="bg-card/80 backdrop-blur-md border border-card-border rounded-2xl p-6">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center border border-emerald-500/30 shrink-0">
              <Sparkles className="w-6 h-6 text-emerald-400" />
            </div>
            <div className="flex-1">
              <h2 className="text-lg font-semibold text-foreground mb-1">Comprehensive Standing Analysis</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Analyzing all your quiz results and individual feedback reports to build a comprehensive picture of your academic standing, strengths, and weak areas.
              </p>
              {!hasData && !isDataLoading ? (
                <div className="flex items-center gap-2 text-amber-400 text-sm">
                  <AlertTriangle className="w-4 h-4" />
                  Complete some quizzes first to get your analysis.
                </div>
              ) : loading ? (
                <div className="flex items-center gap-3 text-emerald-400 text-sm">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Analyzing your performance across all subjects...
                </div>
              ) : analysis ? (
                <Button
                  className="group relative inline-flex items-center gap-2.5 px-6 py-2.5 rounded-xl font-medium text-sm text-emerald-300 bg-emerald-500/5 border border-emerald-500/20 hover:bg-emerald-500/10 transition-all duration-300"
                  onClick={() => { autoGeneratedRef.current = true; generateAnalysis(); }}
                  disabled={loading || isDataLoading}
                >
                  <Sparkles className="w-4 h-4" />
                  Regenerate Report
                </Button>
              ) : null}
              {error && (
                <p className="text-sm text-red-400 mt-3">{error}</p>
              )}
            </div>
          </div>
        </div>

        {/* Analysis result */}
        {isDataLoading && (
          <div className="bg-card/80 backdrop-blur-md border border-card-border rounded-2xl p-8">
            <div className="space-y-4">
              <Skeleton className="h-6 w-1/2 bg-foreground/5" />
              <Skeleton className="h-4 w-3/4 bg-foreground/5" />
              <Skeleton className="h-4 w-2/3 bg-foreground/5" />
              <Skeleton className="h-32 w-full bg-foreground/5 rounded-xl" />
            </div>
          </div>
        )}

        {analysis && (
          <div ref={reportRef} className="bg-white text-gray-900 p-8 rounded-2xl shadow-lg">
            <div
              className="prose prose-sm max-w-none"
              dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(analysis) }}
            />
          </div>
        )}
      </main>
    </div>
  );
}
