import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { authFetch } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

export default function TutorPdfMarkingReview({ params }: { params?: { quizId?: string; submissionId?: string } }) {
  const submissionId = Number(params?.submissionId);
  const queryClient = useQueryClient(); const { toast } = useToast();
  const key = ["/api/tutor/submission-uploads", submissionId, "ai-review"];
  const { data, isLoading } = useQuery({ queryKey: key, enabled: Number.isInteger(submissionId), queryFn: async () => { const res = await authFetch(`/api/tutor/submission-uploads/${submissionId}/ai-review`); if (!res.ok) throw new Error("Failed to load AI review"); return res.json(); } });
  const approve = useMutation({ mutationFn: async () => { const res = await authFetch(`/api/tutor/submission-uploads/${submissionId}/ai-approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }); if (!res.ok) throw new Error("Approval failed"); return res.json(); }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: key }); toast({ title: "Result approved and released" }); } });
  const manual = useMutation({ mutationFn: async () => { const score = Number(window.prompt("Score?", "0")); const maxScore = Number(window.prompt("Max score?", "1")); const feedback = window.prompt("Feedback?", "Marked by tutor.") ?? ""; const res = await authFetch(`/api/tutor/submission-uploads/${submissionId}/ai-manual-override`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ score, maxScore, feedback }) }); if (!res.ok) throw new Error("Manual override failed"); return res.json(); }, onSuccess: () => toast({ title: "Manual override saved" }) });
  if (isLoading) return <div className="p-6">Loading AI review…</div>;
  return <main className="max-w-5xl mx-auto p-4 md:p-8 space-y-4"><h1 className="text-2xl font-bold">AI-assisted PDF marking review</h1><section className="rounded-xl border p-4 bg-background"><p className="text-sm text-muted-foreground">Submission version {data?.submission?.submissionVersion ?? "—"}</p><p className="text-lg font-semibold">Proposed score: {data?.run?.proposedScore ?? "—"}/{data?.run?.maxScore ?? "—"}</p><p className="text-sm">Status: {data?.submission?.aiMarkingStatus ?? data?.submission?.status}</p></section><section className="grid gap-3"><h2 className="font-semibold">Review items</h2>{(data?.reviewItems ?? []).length === 0 ? <p className="text-sm text-muted-foreground">No unresolved disagreement details are available.</p> : data.reviewItems.map((item: any) => <article key={item.id} className="rounded-xl border p-3"><p className="font-medium">{item.questionLabel} · {item.rubricItemId}</p><p className="text-sm text-muted-foreground">{item.reasonCode}</p></article>)}</section><section className="grid gap-3"><h2 className="font-semibold">Annotations</h2>{(data?.annotations ?? []).map((a: any) => <p key={a.id} className="text-sm">Page {a.pageNumber}: {a.annotationType} — {a.explanation}</p>)}</section><div className="flex gap-2"><Button onClick={() => approve.mutate()} disabled={approve.isPending}>Approve and release</Button><Button variant="outline" onClick={() => manual.mutate()} disabled={manual.isPending}>Manual override</Button></div></main>;
}
