import type { Request, Response } from "express";
import { sendInternalError } from "../../utils/apiErrors";
import { logError, requestLogContext } from "../../utils/logging";
import * as service from "./service";
import { parseId, reviewPatchSchema } from "./validators";
function tutorId(req: Request) { return (req as any).tutorId as string; }
function sendDomain(res: Response, err: service.TutorQuizError) { return res.status(err.status).json({ message: err.message }); }
export async function list(req: Request, res: Response) { try { return res.json(await service.listOwned(tutorId(req))); } catch (err: any) { return sendInternalError(req, res, err, "routes.failed_to_fetch_quizzes", "Failed to fetch quizzes"); } }
export async function clone(req: Request, res: Response) { try { return res.status(201).json(await service.clone(parseId(req.params.quizId), tutorId(req))); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "tutor.quizzes.clone", "Failed to duplicate assessment."); } }
export async function create(req: Request, res: Response) { try { return res.json(await service.create(tutorId(req), req.body)); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "routes.failed_to_create_quiz", "Failed to create quiz"); } }
export async function detail(req: Request, res: Response) { try { return res.json(await service.detail(parseId(req.params.quizId), tutorId(req))); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "routes.failed_to_fetch_quiz", "Failed to fetch quiz"); } }
export async function managementDetails(req: Request, res: Response) { try { return res.json(await service.managementDetails(parseId(req.params.quizId), tutorId(req))); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); logError("route.quiz_details_failed", err, { ...requestLogContext(req as any), severity: "high", module: "routes", component: "quizDetails", quizId: req.params.quizId }); return sendInternalError(req, res, err, "routes.failed_to_fetch_quiz_details", "Failed to fetch quiz details"); } }
export async function review(req: Request, res: Response) { const quizId = parseId(req.params.quizId); if (isNaN(quizId)) return res.status(400).json({ message: "Invalid quiz ID" }); try { return res.json(await service.reviewQuestions(quizId, tutorId(req))); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "tutor.quizzes.review", "Failed to load questions for review."); } }
export async function updateReview(req: Request, res: Response) { const quizId = parseId(req.params.quizId); const questionId = parseId(req.params.questionId); if (isNaN(quizId) || isNaN(questionId)) return res.status(400).json({ message: "Invalid ID" }); const parsed = reviewPatchSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Invalid request", errors: parsed.error.flatten() }); try { return res.json(await service.updateReview(quizId, questionId, tutorId(req), parsed.data)); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "tutor.quizzes.review.patch", "Failed to update question."); } }
export async function update(req: Request, res: Response) { try { return res.json(await service.updateMetadata(parseId(req.params.quizId), tutorId(req), req.body)); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "routes.failed_to_update_quiz", "Failed to update quiz"); } }
export async function archive(req: Request, res: Response) { try { return res.json(await service.archive(parseId(req.params.quizId), tutorId(req))); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "routes.failed_to_toggle_archive", "Failed to toggle archive"); } }
export async function remove(req: Request, res: Response) { try { return res.json(await service.remove(parseId(req.params.quizId), tutorId(req))); } catch (err: any) { if (err instanceof service.TutorQuizError) return sendDomain(res, err); return sendInternalError(req, res, err, "routes.failed_to_delete_quiz", "Failed to delete quiz"); } }
