import type { Request, Response } from "express";
import { sendInternalError } from "../../utils/apiErrors";
import * as service from "./service";
const id=(v:any)=>parseInt(String(v),10); const tutor=(req:Request)=>(req as any).tutorId as string; const send=(res:Response,e:service.AssignmentError)=>res.status(e.status).json({message:e.message});
export async function assign(req:Request,res:Response){try{return res.json(await service.assign(id(req.params.quizId),tutor(req),req.body));}catch(e:any){if(e instanceof service.AssignmentError)return send(res,e);return sendInternalError(req,res,e,"routes.failed_to_assign_quiz","Failed to assign quiz");}}
export async function unassign(req:Request,res:Response){try{return res.json(await service.unassign(id(req.params.quizId),String(req.params.studentId),tutor(req)));}catch(e:any){if(e instanceof service.AssignmentError)return send(res,e);return sendInternalError(req,res,e,"routes.failed_to_unassign_student","Failed to unassign student");}}
export async function revoke(req:Request,res:Response){try{return res.json(await service.revoke(id(req.params.quizId),String(req.params.studentId),tutor(req)));}catch(e:any){if(e instanceof service.AssignmentError)return send(res,e);return sendInternalError(req,res,e,"routes.failed_to_revoke_assignment","Failed to revoke assignment");}}
export async function updateDueDate(req:Request,res:Response){try{return res.json(await service.updateDueDate(id(req.params.quizId),tutor(req),req.body?.dueDate));}catch(e:any){if(e instanceof service.AssignmentError)return send(res,e);return sendInternalError(req,res,e,"routes.failed_to_update_due_date","Failed to update due date");}}
export async function extend(req:Request,res:Response){try{return res.json(await service.extend(id(req.params.quizId),tutor(req),req.body?.hours));}catch(e:any){if(e instanceof service.AssignmentError)return send(res,e);return sendInternalError(req,res,e,"routes.failed_to_extend_deadline","Failed to extend deadline");}}
export async function list(req:Request,res:Response){try{return res.json(await service.list(id(req.params.quizId),tutor(req)));}catch(e:any){if(e instanceof service.AssignmentError)return send(res,e);return sendInternalError(req,res,e,"routes.failed_to_fetch_assignments","Failed to fetch assignments");}}
