import { storage } from "../../storage";
import { computeDefaultDueDate } from "@shared/dueDate";
export class AssignmentError extends Error { constructor(public status: number, message: string) { super(message); } }
function sanitizeStudentIds(value: unknown): string[] { return Array.isArray(value) ? Array.from(new Set(value.map((id) => String(id || "").trim()).filter(Boolean))) : []; }
async function owned(quizId: number, tutorId: string, notFoundAs403 = false) { const quiz = await storage.getSomaQuiz(quizId); if (!quiz) throw new AssignmentError(notFoundAs403 ? 403 : 404, "Quiz not found"); if (quiz.authorId !== tutorId) throw new AssignmentError(403, "Access denied"); return quiz; }
export async function assign(quizId: number, tutorId: string, body: any) {
  const studentIds = sanitizeStudentIds(body?.studentIds); const rawDueDate = body?.dueDate; let dueDate = rawDueDate ? new Date(rawDueDate) : null; if (dueDate && isNaN(dueDate.getTime())) throw new AssignmentError(400, "Invalid dueDate format"); if (studentIds.length === 0) throw new AssignmentError(400, "studentIds array required");
  const quiz = await storage.getSomaQuiz(quizId); if (!quiz || quiz.isArchived) throw new AssignmentError(404, "Quiz not found"); if (quiz.authorId !== tutorId) throw new AssignmentError(403, "Access denied"); if (!dueDate) dueDate = computeDefaultDueDate(quiz.createdAt); if (quiz.status !== "published") await storage.updateSomaQuiz(quizId, { status: "published" });
  const adopted = await storage.getAdoptedStudents(tutorId); const adoptedById = new Map(adopted.map((s) => [s.id, s])); const notAdoptedIds = studentIds.filter((id) => !adoptedById.has(id)); const validIds = studentIds.filter((id) => adoptedById.has(id)); if (validIds.length === 0) throw new AssignmentError(400, "None of the provided students are adopted by you");
  const existing = await storage.getQuizAssignmentsForQuiz(quizId); const existingIds = new Set(existing.map((a) => a.student.id)); const alreadyAssignedIds = validIds.filter((id) => existingIds.has(id)); const toCreateIds = validIds.filter((id) => !existingIds.has(id)); const newAssignments = toCreateIds.length > 0 ? await storage.createQuizAssignments(quizId, toCreateIds, dueDate) : [];
  const perStudent = studentIds.map((id) => { const student = adoptedById.get(id); const name = student?.displayName || student?.email || id; const email = student?.email || null; if (!adoptedById.has(id)) return { studentId: id, name, email, status: "not_adopted" as const }; if (existingIds.has(id)) return { studentId: id, name, email, status: "already_assigned" as const }; const persisted = newAssignments.some((a: any) => a.studentId === id); return { studentId: id, name, email, status: persisted ? ("assigned" as const) : ("failed" as const) }; });
  await Promise.all(toCreateIds.map((studentId) => storage.createStudentNotification({ studentId, type: "assignment_new", title: "New assessment assigned", message: dueDate ? `Your tutor assigned "${quiz.title}". It's due ${dueDate.toDateString()}.` : `Your tutor assigned "${quiz.title}". Take it whenever you're ready.`, payload: { quizId: quiz.id, quizTitle: quiz.title, dueDate: dueDate ? dueDate.toISOString() : null } }).catch((err) => console.error("[Assign Notification] failed:", err))));
  return { requested: studentIds.length, assigned: newAssignments.length, alreadyAssigned: alreadyAssignedIds.length, notAdopted: notAdoptedIds.length, failed: perStudent.filter((p) => p.status === "failed").length, assignments: newAssignments, perStudent };
}
export async function unassign(quizId: number, studentId: string, tutorId: string) { await owned(quizId, tutorId); await storage.deleteQuizAssignment(quizId, studentId); return { success: true, message: "Student unassigned" }; }
export async function revoke(quizId: number, studentId: string, tutorId: string) { await owned(quizId, tutorId, true); await storage.deleteQuizAssignment(quizId, studentId); return { success: true }; }
export async function updateDueDate(quizId: number, tutorId: string, dueDate: unknown) { await owned(quizId, tutorId); const parsedDate = dueDate ? new Date(dueDate as any) : null; if (parsedDate && isNaN(parsedDate.getTime())) throw new AssignmentError(400, "Invalid date format"); const updated = await storage.updateQuizAssignmentsDueDate(quizId, parsedDate); return { success: true, updated }; }
export async function extend(quizId: number, tutorId: string, hoursRaw: unknown) { const quiz = await storage.getSomaQuiz(quizId); if (!quiz) throw new AssignmentError(404, "Quiz not found"); if (quiz.authorId !== tutorId) throw new AssignmentError(403, "Only the author can extend deadlines"); const hours = Number(hoursRaw) || 24; const updated = await storage.extendQuizAssignmentDeadlines(quizId, hours); return { success: true, message: `Extended deadline by ${hours}h for ${updated} assignment(s)`, updated }; }
export async function list(quizId: number, tutorId: string) { await owned(quizId, tutorId); return storage.getQuizAssignmentsForQuiz(quizId); }
