import crypto from "crypto";
import { storage } from "../storage";
import { getPdfMarkingConfig } from "../services/pdfMarkingConfig";
import { calculateRetryBackoffMs } from "../services/pdfReconciliation";
import { logInfo, logWarn } from "../utils/logging";

export class PdfMarkingWorker {
  private timer: NodeJS.Timeout | null = null; private stopped = false; private readonly workerId = `pdf-${process.pid}-${crypto.randomUUID()}`;
  constructor(private readonly pollMs = Number(process.env.PDF_MARKING_POLL_MS || 5000)) {}
  start() { const cfg = getPdfMarkingConfig(); if (!cfg.enabled || !cfg.workerEnabled) return; this.stopped = false; const tick = async () => { if (this.stopped) return; await this.processOnce().catch((e) => logWarn("pdf_marking_worker_tick_failed", { error: e?.message })); this.timer = setTimeout(tick, this.pollMs); this.timer.unref?.(); }; tick(); logInfo("pdf_marking_worker_started", { workerId: this.workerId }); }
  stop() { this.stopped = true; if (this.timer) clearTimeout(this.timer); }
  async processOnce() { const staleBefore = new Date(Date.now() - Number(process.env.PDF_MARKING_LEASE_MS || 15 * 60_000)); const job = await storage.claimNextPdfMarkingJob(this.workerId, staleBefore); if (!job) return; try { if (job.jobType === "prepare_assessment") await this.prepare(job.id, job.quizId!); else if (job.jobType === "mark_submission") await this.mark(job.id, job.submissionUploadId!, job.rubricVersionId!); else await storage.updatePdfMarkingJob(job.id, { status: "completed", completedAt: new Date() } as any); } catch (e: any) { const retry = job.attempts < job.maxAttempts; await storage.updatePdfMarkingJob(job.id, { status: retry ? "retry_wait" : "failed", availableAt: new Date(Date.now() + calculateRetryBackoffMs(job.attempts)), lastErrorCode: retry ? "retryable" : "terminal", lastError: String(e?.message || e).slice(0, 1000) } as any); } }
  private async prepare(jobId: number, quizId: number) { const quiz = await storage.getSomaQuiz(quizId); if (!quiz) throw new Error("quiz_not_found"); const existing = await storage.getPdfRubricVersionsByQuiz(quizId); const rubricJson = { assessmentTitle: quiz.title, totalMarks: 1, questions: [{ questionId: "q1", label: "Q1", prompt: "Tutor must review and edit this generated draft rubric before use.", pageReferences: [1], maximumMarks: 1, answerType: "short_text", syllabusTags: [quiz.subject, quiz.level, quiz.syllabus].filter(Boolean), acceptedAlternatives: [], rubricItems: [{ rubricItemId: "q1-1", sequence: 1, description: "Award according to the tutor-approved marking scheme.", maximumMarks: 1, markType: "independent", dependencies: [], errorCarriedForwardAllowed: false, unitsRequired: false }] }] }; const rubric = await storage.createPdfRubricVersion({ quizId, version: (existing[0]?.version ?? 0) + 1, source: "ai_generated", status: "draft", totalMarks: 1, rubricJson, modelMetadata: { generatedBy: "pdfMarkingWorker", promptVersion: "pdf-dual-ai-v1" } } as any); await storage.upsertPdfAssessmentConfig({ quizId, preparationStatus: "needs_review", activeRubricVersionId: rubric.id, preparedAt: new Date() } as any); await storage.updatePdfMarkingJob(jobId, { status: "completed", completedAt: new Date() } as any); }
  private async mark(jobId: number, submissionUploadId: number, rubricVersionId: number) { const upload = await storage.getSubmissionUpload(submissionUploadId); const rubric = await storage.getPdfRubricVersion(rubricVersionId); if (!upload || !rubric) throw new Error("input_not_found"); await storage.markSubmissionUpload(upload.id, { score: null, maxScore: null, feedback: null, status: "submitted", markedAt: null, aiMarkingStatus: "blocked_setup" }); await storage.updatePdfMarkingJob(jobId, { status: "cancelled", lastErrorCode: "adapter_disabled", lastError: "PDF dual marking adapter is disabled; submission remains available for manual tutor marking.", completedAt: new Date() } as any); }
}
let worker: PdfMarkingWorker | null = null;
export function startPdfMarkingWorker() { if (!worker) worker = new PdfMarkingWorker(); worker.start(); return worker; }
export function stopPdfMarkingWorker() { worker?.stop(); worker = null; }
