import type { Request, Response } from "express";
import { sendInternalError } from "../../utils/apiErrors";
import * as service from "./service";
import { firstZodMessage, levelsQuerySchema, subjectsQuerySchema, topicContextQuerySchema, topicsQuerySchema } from "./validators";
export async function examiningBodies(req: Request, res: Response) { try { return res.json(await service.listBodies()); } catch (err: any) { return sendInternalError(req, res, err, "routes.failed_to_list_examining_bodies", "Failed to list examining bodies"); } }
export async function levels(req: Request, res: Response) { const parsed = levelsQuerySchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ message: firstZodMessage(parsed.error) }); try { return res.json(await service.listLevels(parsed.data.body)); } catch (err: any) { return sendInternalError(req, res, err, "routes.failed_to_list_levels", "Failed to list levels"); } }
export async function authSubjects(req: Request, res: Response) { try { return res.json(await service.listPublicSubjectNames()); } catch (err: any) { return sendInternalError(req, res, err, "routes.failed_to_list_subjects", "Failed to list subjects"); } }
export async function subjects(req: Request, res: Response) { const parsed = subjectsQuerySchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ message: firstZodMessage(parsed.error) }); try { return res.json(await service.listSubjects(parsed.data.body, parsed.data.level)); } catch (err: any) { return sendInternalError(req, res, err, "routes.failed_to_list_subjects", "Failed to list subjects"); } }
export async function topics(req: Request, res: Response) { const parsed = topicsQuerySchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ message: firstZodMessage(parsed.error) }); try { const result = await service.listTopicResponse(parsed.data.body, parsed.data.level, parsed.data.subject); if (!result) return res.status(404).json({ message: "No syllabus matches the given body/level/subject" }); return res.json(result); } catch (err: any) { return sendInternalError(req, res, err, "routes.failed_to_list_topics", "Failed to list topics"); } }
export async function topicContext(req: Request, res: Response) { const parsed = topicContextQuerySchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ message: firstZodMessage(parsed.error) }); try { return res.json(await service.topicContext(parsed.data.topicIds)); } catch (err: any) { return sendInternalError(req, res, err, "routes.failed_to_fetch_topic_context", "Failed to fetch topic context"); } }
