import React, { useId } from "react";
import type { GraphQuestionSpec } from "@shared/schema";

// ── Layout constants ──────────────────────────────────────────────────────────
const WIDTH  = 620;
const HEIGHT = 340;
// left=72 gives enough room for labels like "−100" without clipping
const M = { top: 36, right: 56, bottom: 36, left: 72 };

const plotLeft   = M.left;
const plotRight  = WIDTH  - M.right;
const plotTop    = M.top;
const plotBottom = HEIGHT - M.bottom;
const plotW      = plotRight - plotLeft;   // 492
const plotH      = plotBottom - plotTop;   // 268

const CURVE_COLORS = [
  "#38bdf8", // sky blue
  "#a78bfa", // violet
  "#34d399", // emerald
  "#fb923c", // orange
  "#f87171", // rose
  "#facc15", // yellow
];

// ── Nice tick interval ────────────────────────────────────────────────────────
// Always produces 4–10 readable, "round number" ticks regardless of range size.
function niceInterval(span: number): number {
  if (span <= 0) return 1;
  const rough = span / 8;
  const mag   = Math.pow(10, Math.floor(Math.log10(rough)));
  const norm  = rough / mag;
  const nice  = norm <= 1 ? 1 : norm <= 2 ? 2 : norm <= 3 ? 2.5 : norm <= 7.5 ? 5 : 10;
  return parseFloat((nice * mag).toPrecision(6));
}

// ── Safe equation evaluator ───────────────────────────────────────────────────
// Injects the full Math object so equations like sin(x), cos(x), exp(x),
// sqrt(x), log(x), abs(x), PI etc. work without any extra pre-processing.
function evaluateEquation(eq: string, x: number): number | null {
  const expr = eq
    .replace(/^y\s*=\s*/i, "")           // strip "y = " prefix
    .replace(/\^/g, "**")                  // ^ → **
    .replace(/([0-9])\s*x/g, "$1*x")      // 2x → 2*x
    .replace(/([0-9])\s*\(/g, "$1*(");    // 2( → 2*(
  try {
    // Destructure Math so authors can write sin(x) instead of Math.sin(x).
    // eslint-disable-next-line no-new-func
    const fn = new Function(
      "x",
      `"use strict";
       const {abs,acos,acosh,asin,asinh,atan,atanh,atan2,cbrt,ceil,clz32,cos,cosh,
              exp,expm1,floor,fround,hypot,imul,log,log10,log1p,log2,max,min,pow,
              random,round,sign,sin,sinh,sqrt,tan,tanh,trunc,
              PI,E,LN2,LN10,LOG2E,LOG10E,SQRT2,SQRT1_2} = Math;
       return (${expr});`,
    ) as (x: number) => number;
    const v = fn(x);
    return Number.isFinite(v) ? v : null;
  } catch {
    return null;
  }
}

// ── SVG path with pen-lift on discontinuities ─────────────────────────────────
// Returns null (not "") when nothing can be plotted — callers skip rendering entirely.
function buildCurvePath(
  eq: string,
  xMin: number, xMax: number,
  yMin: number, yMax: number,
  xToSvg: (x: number) => number,
  yToSvg: (y: number) => number,
  numSamples = 600,
): string | null {
  const ySpan  = yMax - yMin;
  const parts: string[] = [];
  let penDown  = false;
  let prevY: number | null = null;

  for (let i = 0; i <= numSamples; i++) {
    const x = xMin + ((xMax - xMin) * i) / numSamples;
    const y = evaluateEquation(eq, x);

    if (y === null) { penDown = false; prevY = null; continue; }

    // Lift pen on asymptote-like discontinuity
    if (prevY !== null && Math.abs(y - prevY) > ySpan * 4) penDown = false;

    parts.push(penDown
      ? `L ${xToSvg(x).toFixed(2)} ${yToSvg(y).toFixed(2)}`
      : `M ${xToSvg(x).toFixed(2)} ${yToSvg(y).toFixed(2)}`);
    penDown = true;
    prevY   = y;
  }
  return parts.length > 0 ? parts.join(" ") : null;
}

// ── Client-side graphSpec validator ───────────────────────────────────────────
function isValidSpec(spec: GraphQuestionSpec): boolean {
  if (!spec) return false;
  const [xMin, xMax] = spec.xRange;
  const [yMin, yMax] = spec.yRange;
  if (!Number.isFinite(xMin) || !Number.isFinite(xMax) || xMin >= xMax) return false;
  if (!Number.isFinite(yMin) || !Number.isFinite(yMax) || yMin >= yMax) return false;
  const hasEquation = typeof spec.equation === "string" && spec.equation.trim().length > 0;
  const hasCurves   = Array.isArray(spec.curves) && spec.curves.length > 0;
  const hasPoints   = Array.isArray(spec.points)  && spec.points.length > 0;
  if (!hasEquation && !hasCurves && !hasPoints) return false;
  return true;
}

// ── Equation display label ─────────────────────────────────────────────────────
// Converts a raw JS equation expression to a human-readable math string.
// Used as a fallback when the AI has not supplied a spec.label.
// Handles the most common patterns generated by the AI:
//   Math.sin(x * Math.PI / 180) → sin x°     (trig in degrees)
//   Math.sin(x)                 → sin x
//   Math.cos(x)                 → cos x
//   Math.tan(x)                 → tan x
//   Math.exp(x)                 → eˣ
//   Math.log(x)                 → ln x
//   Math.sqrt(x)                → √x
//   Math.abs(x)                 → |x|
//   x**2                        → x²
//   x**3                        → x³
//   2*x                         → 2x
//   Math.PI                     → π
function prettyEquation(eq: string): string {
  let s = eq
    .replace(/^y\s*=\s*/i, "")            // strip "y = " prefix
    .trim();

  // Trig in degrees: sin/cos/tan(x * Math.PI / 180) → sin x° etc.
  s = s.replace(/Math\.(sin|cos|tan)\(\s*x\s*\*\s*Math\.PI\s*\/\s*180\s*\)/gi,
    (_, fn) => `${fn} x°`);
  s = s.replace(/Math\.(sin|cos|tan)\(\s*Math\.PI\s*\*\s*x\s*\/\s*180\s*\)/gi,
    (_, fn) => `${fn} x°`);

  // Trig in radians: sin(x) etc.
  s = s.replace(/Math\.(sin|cos|tan)\(\s*x\s*\)/gi, (_, fn) => `${fn} x`);
  s = s.replace(/Math\.(sin|cos|tan)\(/gi, (_, fn) => `${fn}(`);

  // Exponential / log
  s = s.replace(/Math\.exp\(\s*x\s*\)/gi, "eˣ");
  s = s.replace(/Math\.exp\(/gi, "exp(");
  s = s.replace(/Math\.log\(\s*x\s*\)/gi, "ln x");
  s = s.replace(/Math\.log\(/gi, "ln(");
  s = s.replace(/Math\.log10\(\s*x\s*\)/gi, "log x");
  s = s.replace(/Math\.log10\(/gi, "log₁₀(");

  // sqrt / abs
  s = s.replace(/Math\.sqrt\(\s*x\s*\)/gi, "√x");
  s = s.replace(/Math\.sqrt\(/gi, "√(");
  s = s.replace(/Math\.abs\(\s*x\s*\)/gi, "|x|");
  s = s.replace(/Math\.abs\(/gi, "|");

  // Constants
  s = s.replace(/Math\.PI/g, "π");
  s = s.replace(/Math\.E\b/g, "e");

  // Powers: x**2 → x², x**3 → x³, x**n → xⁿ
  const supMap: Record<string, string> = {"0":"⁰","1":"¹","2":"²","3":"³","4":"⁴","5":"⁵","6":"⁶","7":"⁷","8":"⁸","9":"⁹"};
  s = s.replace(/x\*\*(\d)/g, (_, d) => `x${supMap[d] ?? `^${d}`}`);
  s = s.replace(/\*\*/g, "^");

  // Implicit multiplication: 2*x → 2x, 3*(... → 3(...
  s = s.replace(/(\d)\s*\*\s*x/g, "$1x");
  s = s.replace(/(\d)\s*\*\s*\(/g, "$1(");

  // Remaining bare * → nothing (or keep for clarity)
  s = s.replace(/\s*\*\s*/g, "·");

  return s.trim();
}

function equationDisplayLabel(spec: { equation?: string; label?: string }): string {
  if (spec.label) {
    // Use the AI-supplied human-readable label, strip leading "y = " if present
    return spec.label.replace(/^y\s*=\s*/i, "").trim();
  }
  if (spec.equation) {
    return prettyEquation(spec.equation);
  }
  return "";
}

// ── Component ─────────────────────────────────────────────────────────────────
export default function GraphPlot({ spec }: { spec: GraphQuestionSpec }) {
  // Generate unique IDs per instance so multiple graphs on the same page
  // never share clipPath or marker IDs — SVG ID conflicts cause wrong clipping
  // and missing arrowheads on all but the first graph.
  const uid        = useId().replace(/:/g, "");
  const clipId     = `plot-clip-${uid}`;
  const markerId   = `arrowhead-${uid}`;

  // Validate spec client-side before attempting to render
  if (!isValidSpec(spec)) {
    return (
      <div
        className="rounded-2xl border border-slate-700/50 bg-slate-900/60 p-6 text-center"
        data-testid="graph-invalid"
      >
        <p className="text-slate-400 text-sm">Graph specification is invalid or incomplete.</p>
      </div>
    );
  }

  const [xMin, xMax] = spec.xRange;
  const [yMin, yMax] = spec.yRange;
  const axisLabels   = spec.axisLabels ?? { x: "x", y: "y" };

  // ── Coordinate transforms using the AI's exact ranges ────────────────────
  const xToSvg = (x: number) =>
    plotLeft  + ((x - xMin) / (xMax - xMin)) * plotW;
  const yToSvg = (y: number) =>
    plotBottom - ((y - yMin) / (yMax - yMin)) * plotH;

  // Axes clamped to plot area (handles ranges that don't include 0)
  const xAxisY = Math.max(plotTop,  Math.min(plotBottom, yToSvg(0)));
  const yAxisX = Math.max(plotLeft, Math.min(plotRight,  xToSvg(0)));

  // ── Smart tick intervals (independent per axis) ───────────────────────────
  const xTick = niceInterval(xMax - xMin);
  const yTick = niceInterval(yMax - yMin);

  const makeTicks = (lo: number, hi: number, step: number) => {
    const start = Math.ceil(lo / step) * step;
    const out: number[] = [];
    for (let v = start; v <= hi + 1e-9; v = parseFloat((v + step).toPrecision(10))) {
      out.push(parseFloat(v.toPrecision(10)));
    }
    return out;
  };
  const xTicks = makeTicks(xMin, xMax, xTick);
  const yTicks = makeTicks(yMin, yMax, yTick);

  // ── Curves ────────────────────────────────────────────────────────────────
  const allCurves: { equation: string; label?: string; color: string }[] = [];
  if (spec.curves && spec.curves.length > 0) {
    spec.curves.forEach((c, i) => allCurves.push({
      equation: c.equation,
      label:    c.label,
      color:    c.color ?? CURVE_COLORS[i % CURVE_COLORS.length],
    }));
  } else if (spec.equation) {
    allCurves.push({ equation: spec.equation, color: CURVE_COLORS[0] });
  }

  // ── Equation label (single-curve) — shown italic on graph ────────────────
  // Only shown when there is exactly one curve derived from spec.equation
  // (not spec.curves) to avoid collision with the multi-curve legend below.
  const showSingleEquationLabel =
    allCurves.length === 1 && !!spec.equation && !spec.curves?.length;
  const singleEquationText = showSingleEquationLabel
    ? equationDisplayLabel(spec)
    : null;

  // Pick a position for the label: upper-right area of the plot, away from Y-axis label
  const eqLabelX = plotRight - 6;
  const eqLabelY = plotTop + 18;

  const showLegend    = allCurves.length > 1 && allCurves.some((c) => c.label);
  const legendEntries = showLegend ? allCurves.filter((c) => c.label) : [];
  const plotPoints    = [...(spec.points || []), ...(spec.highlightedPoints || [])];
  const TICK_SIZE     = 4; // half-length of tick cross-hairs (px)

  // Y-tick label x-position: left of y-axis, but at least 4px inside SVG viewport
  const yLabelX = Math.max(4, yAxisX - 9);

  return (
    <div
      className="rounded-2xl border border-cyan-500/20 bg-slate-950/70 p-3 md:p-4"
      data-testid="graph-plot"
    >
      {/*
        SVG sizing: `w-full` + no fixed height → browser computes height from viewBox aspect
        ratio (620:340 ≈ 1.82:1), so the graph scales proportionally on every screen size.
        A max-width wrapper caps the graph at its natural 620 px width on large monitors.
      */}
      <div className="w-full max-w-[620px] mx-auto">
      <svg
        viewBox={`0 0 ${WIDTH} ${HEIGHT}`}
        className="w-full block"
        role="img"
        aria-label="Cartesian graph"
      >
        <defs>
          {/*
            Unique clipPath ID per instance prevents conflicts when multiple
            GraphPlot components render on the same page.
          */}
          <clipPath id={clipId}>
            <rect x={plotLeft} y={plotTop} width={plotW} height={plotH} />
          </clipPath>

          {/*
            Unique marker ID — same reason as clipPath above.
            orient="auto" rotates to match line direction:
              X axis (→ rightward)  →  0°
              Y axis (↑ upward, y2 < y1 in SVG coords) → −90°
          */}
          <marker
            id={markerId}
            markerWidth="8" markerHeight="8"
            refX="8" refY="4"
            orient="auto"
          >
            <path d="M0,1 L8,4 L0,7 z" fill="rgba(226,232,240,0.60)" />
          </marker>
        </defs>

        {/* ── Grid lines ────────────────────────────────────────────────── */}
        <g clipPath={`url(#${clipId})`}>
          {spec.showGrid && xTicks.map((x) => (
            <line key={`vg-${x}`}
              x1={xToSvg(x)} x2={xToSvg(x)} y1={plotTop} y2={plotBottom}
              stroke="rgba(148,163,184,0.10)" strokeWidth="1"
            />
          ))}
          {spec.showGrid && yTicks.map((y) => (
            <line key={`hg-${y}`}
              x1={plotLeft} x2={plotRight} y1={yToSvg(y)} y2={yToSvg(y)}
              stroke="rgba(148,163,184,0.10)" strokeWidth="1"
            />
          ))}
        </g>

        {/* ── X axis → ──────────────────────────────────────────────────── */}
        <line
          x1={plotLeft} x2={plotRight + 5}
          y1={xAxisY}   y2={xAxisY}
          stroke="rgba(226,232,240,0.55)" strokeWidth="1.5"
          markerEnd={`url(#${markerId})`}
        />

        {/* ── Y axis ↑ (drawn bottom→top so marker-end points up) ─────── */}
        <line
          x1={yAxisX} x2={yAxisX}
          y1={plotBottom} y2={plotTop - 5}
          stroke="rgba(226,232,240,0.55)" strokeWidth="1.5"
          markerEnd={`url(#${markerId})`}
        />

        {/* ── Tick marks on X axis ──────────────────────────────────────── */}
        {xTicks.map((x) => {
          const sx = xToSvg(x);
          if (sx < plotLeft - 1 || sx > plotRight + 1) return null;
          return (
            <line key={`xtk-${x}`}
              x1={sx} x2={sx}
              y1={xAxisY - TICK_SIZE} y2={xAxisY + TICK_SIZE}
              stroke="rgba(148,163,184,0.6)" strokeWidth="1"
            />
          );
        })}

        {/* ── Tick marks on Y axis ──────────────────────────────────────── */}
        {yTicks.map((y) => {
          const sy = yToSvg(y);
          if (sy < plotTop - 1 || sy > plotBottom + 1) return null;
          return (
            <line key={`ytk-${y}`}
              x1={yAxisX - TICK_SIZE} x2={yAxisX + TICK_SIZE}
              y1={sy} y2={sy}
              stroke="rgba(148,163,184,0.6)" strokeWidth="1"
            />
          );
        })}

        {/* ── X tick labels ─────────────────────────────────────────────── */}
        {xTicks.map((x) => {
          const sx = xToSvg(x);
          if (sx < plotLeft - 1 || sx > plotRight + 1) return null;
          // Skip origin label when both axes are visible (avoid "0" at intersection)
          const skipOrigin = x === 0 && yMin < 0 && yMax > 0 && xMin < 0 && xMax > 0;
          return !skipOrigin ? (
            <text key={`xl-${x}`}
              x={sx} y={xAxisY + 16}
              textAnchor="middle" fill="#94a3b8" fontSize="11"
            >
              {x}
            </text>
          ) : null;
        })}

        {/* ── Y tick labels ─────────────────────────────────────────────── */}
        {yTicks.map((y) => {
          const sy = yToSvg(y);
          if (sy < plotTop - 1 || sy > plotBottom + 1) return null;
          const skipOrigin = y === 0 && xMin < 0 && xMax > 0 && yMin < 0 && yMax > 0;
          return !skipOrigin ? (
            <text key={`yl-${y}`}
              x={yLabelX} y={sy + 4}
              textAnchor="end" fill="#94a3b8" fontSize="11"
            >
              {y}
            </text>
          ) : null;
        })}

        {/* ── Axis name labels (right next to arrowheads) ───────────────── */}
        <text
          x={plotRight + 12} y={xAxisY + 4}
          textAnchor="start" fill="#cbd5e1"
          fontSize="13" fontWeight="600" fontStyle="italic"
        >
          {axisLabels.x}
        </text>
        <text
          x={yAxisX + 6} y={plotTop - 10}
          textAnchor="start" fill="#cbd5e1"
          fontSize="13" fontWeight="600" fontStyle="italic"
        >
          {axisLabels.y}
        </text>

        {/* ── Curves, clipped to plot area ──────────────────────────────── */}
        <g clipPath={`url(#${clipId})`}>
          {allCurves.map((c, i) => {
            const d = buildCurvePath(c.equation, xMin, xMax, yMin, yMax, xToSvg, yToSvg);
            return d ? (
              <path key={`curve-${i}`}
                d={d} fill="none"
                stroke={c.color} strokeWidth="1.8"
                strokeLinecap="round" strokeLinejoin="round"
              />
            ) : null;
          })}

          {plotPoints.map((p, i) => (
            <g key={`pt-${p.x}-${p.y}-${i}`}>
              <circle
                cx={xToSvg(p.x)} cy={yToSvg(p.y)} r="4.5"
                fill="#a78bfa" stroke="#1e1b4b" strokeWidth="1.2"
              />
              {p.label && (
                <text
                  x={xToSvg(p.x) + 8} y={yToSvg(p.y) - 6}
                  fill="#e2e8f0" fontSize="11"
                >
                  {p.label}
                </text>
              )}
            </g>
          ))}
        </g>

        {/* ── Single-curve equation label — italic, upper-right ─────────── */}
        {singleEquationText && (
          <text
            x={eqLabelX} y={eqLabelY}
            textAnchor="end"
            fill={CURVE_COLORS[0]}
            fontSize="12"
            fontStyle="italic"
            fontWeight="500"
            opacity="0.90"
          >
            y = {singleEquationText}
          </text>
        )}
      </svg>

      {/* ── Legend — HTML below the SVG (no in-plot overlap) ─────────────── */}
      {showLegend && legendEntries.length > 0 && (
        <div className="flex flex-wrap items-center justify-center gap-x-5 gap-y-1 mt-2 pt-2 border-t border-white/5">
          {legendEntries.map((c, i) => (
            <div key={i} className="flex items-center gap-2">
              <span
                className="inline-block rounded-full flex-shrink-0"
                style={{ width: 20, height: 2, background: c.color }}
              />
              <span className="text-xs text-slate-300 italic whitespace-nowrap">{c.label}</span>
            </div>
          ))}
        </div>
      )}
      </div>{/* end max-w-[620px] wrapper */}
    </div>
  );
}
