import type { Request, Response } from "express";
import { sendInternalError } from "../../utils/apiErrors";
import { FileStorageError } from "../../services/fileStorage";
import { requireStorageConfigured } from "../fileStorageAccess/service";
import * as service from "./service";
import { parseId } from "./validators";
function tutorId(req: Request) { return (req as any).tutorId as string; }
function userId(req: Request) { return (req as any).authUser.id as string; }
function domain(res: Response, err: service.PdfAttachmentError) { return res.status(err.status).json({ message: err.message }); }
export async function upload(req: Request, res: Response) { try { if (!requireStorageConfigured(res)) return; const quizId = parseId(req.params.quizId); if (isNaN(quizId)) return res.status(400).json({ message: "Invalid quiz ID" }); return res.status(201).json(await service.upload(quizId, tutorId(req), (req as any).file, req.body)); } catch (err: any) { if (err instanceof service.PdfAttachmentError) return domain(res, err); if (err instanceof FileStorageError) return res.status(502).json({ message: "Failed to store file" }); return sendInternalError(req, res, err, "tutor.attachments.create", "Failed to upload attachment."); } }
export async function listForTutor(req: Request, res: Response) { try { const quizId = parseId(req.params.quizId); if (isNaN(quizId)) return res.status(400).json({ message: "Invalid quiz ID" }); return res.json(await service.listForTutor(quizId, tutorId(req))); } catch (err: any) { if (err instanceof service.PdfAttachmentError) return domain(res, err); return sendInternalError(req, res, err, "tutor.attachments.list", "Failed to list attachments."); } }
export async function remove(req: Request, res: Response) { try { const quizId = parseId(req.params.quizId); const attachmentId = parseId(req.params.attachmentId); if (isNaN(quizId) || isNaN(attachmentId)) return res.status(400).json({ message: "Invalid ID" }); return res.json(await service.remove(quizId, attachmentId, tutorId(req))); } catch (err: any) { if (err instanceof service.PdfAttachmentError) return domain(res, err); if (err instanceof FileStorageError) return res.status(502).json({ message: "Failed to delete file" }); return sendInternalError(req, res, err, "tutor.attachments.delete", "Failed to delete attachment."); } }
export async function listForUser(req: Request, res: Response) { try { const quizId = parseId(req.params.quizId); if (isNaN(quizId)) return res.status(400).json({ message: "Invalid quiz ID" }); return res.json(await service.listForUser(quizId, userId(req))); } catch (err: any) { if (err instanceof service.PdfAttachmentError) return domain(res, err); return sendInternalError(req, res, err, "quizzes.attachments.list", "Failed to list attachments."); } }
export async function download(req: Request, res: Response) { try { if (!requireStorageConfigured(res)) return; const quizId = parseId(req.params.quizId); const attachmentId = parseId(req.params.attachmentId); if (isNaN(quizId) || isNaN(attachmentId)) return res.status(400).json({ message: "Invalid ID" }); return res.json(await service.download(quizId, attachmentId, userId(req))); } catch (err: any) { if (err instanceof service.PdfAttachmentError) return domain(res, err); if (err instanceof FileStorageError) return res.status(502).json({ message: "Failed to sign download URL" }); return sendInternalError(req, res, err, "quizzes.attachments.download", "Failed to create download URL."); } }
